window.AG_PAID = [
["Amaryl 1 mg","30 tab","tab",11.5,null,null,"","glimepiride","D",["amaryl mg"]],
["Amaryl 2 mg","30 tab","tab",27,null,null,"","glimepiride","D",[]],
["Amaryl 3 mg","30 tab","tab",30,null,null,"","glimepiride","D",[]],
["Amaryl 4 mg","30 tab","tab",37.5,null,null,"","glimepiride","D",[]],
["Amaryl M 2/500 mg","30 tab","tab",26.5,null,null,"","glimepiride metformin","D",[]],
["Apidra Cartridge","cartridge","cart",null,44,20,"","insulin glulisine","D",[]],
["Atacand 16 mg","14 tab","tab",38.5,null,null,"","candesartan","C",[]],
["Atacand 8 mg","14 tab","tab",27,null,null,"","candesartan","C",[]],
["Atacand Plus 16/12.5","14 tab","tab",42,null,null,"","candesartan hydrochlorothiazide","C",["hct"]],
["Cardura 1 mg","21 tab","tab",23,null,null,"","doxazosin","U",["cardura1mg"]],
["Cardura 4 mg","14 tab","tab",31,null,null,"","doxazosin","U",[]],
["Carnivita Forte","30 tab","tab",20,null,null,"","l-carnitine","V",[]],
["Celebrex 200 mg","10 tab","tab",51.5,null,null,"","celecoxib","P",["celebrix"]],
["Concor 2.5 mg","30 tab","tab",10,null,null,"","bisoprolol","C",[]],
["Concor 5 mg","30 tab","tab",26,null,null,"","bisoprolol","C",[]],
["Cosopt Eye Drops","bottle","drops",52,null,null,"","dorzolamide timolol","OP",[]],
["Coveram 10/10","15 tab","tab",65,null,null,"","perindopril amlodipine","C",[]],
["Coveram 5/5","15 tab","tab",48,null,null,"","perindopril amlodipine","C",[]],
["Coversyl Plus 5/1.25","15 tab","tab",30.5,null,null,"","perindopril indapamide","C",[]],
["Coversyl Plus 10/2.25 mg","15 tab","tab",20,null,null,"","perindopril indapamide","C",[]],
["Coversyl 5 mg","30 tab","tab",53,null,null,"","perindopril","C",[]],
["Glucophage 500 mg","50 tab","tab",14.5,null,null,"","metformin","D",[]],
["Glucophage 1000 XR","30 tab","tab",42.5,null,null,"","metformin extended release","D",[]],
["Glucovance 5/1000","30 tab","tab",20,null,null,"","glibenclamide metformin","D",[]],
["Glucovance 5/500","30 tab","tab",26.5,null,null,"","glibenclamide metformin","D",[]],
["Galvus Met 50/850","30 tab","tab",79.5,null,null,"","vildagliptin metformin","D",["galvus 50/850","galvusmet"]],
["Galvus 50","28 tab","tab",65,null,null,"","vildagliptin","D",["galvuss"]],
["Galvus Met 50/1000","30 tab","tab",86.5,null,null,"","vildagliptin metformin","D",["galvuss 50/1000","galvusmet"]],
["Humalog 100 IU KwikPen","pen","pen",52.87,null,null,"","insulin lispro","D",["kwikpen"]],
["Humalog 100 Cartridge","cartridge","cart",48,null,null,"","insulin lispro","D",[]],
["Humalog Mix 50 KwikPen","pen","pen",null,60,20,"","insulin lispro mix","D",["kwikpen"]],
["Humalog Mix 25 KwikPen","pen","pen",null,60,20,"","insulin lispro mix","D",["kwikpen"]],
["Hyzaar 50 mg","7 tab","tab",22,null,null,"","losartan hydrochlorothiazide","C",[]],
["Isoptin 80 mg","30 tab","tab",6.5,null,null,"","verapamil","C",[]],
["Janumet 50/850","56 tab","tab",175,null,null,"","sitagliptin metformin","D",[]],
["Janumet 50/1000","56 tab","tab",195,null,null,"","sitagliptin metformin","D",[]],
["Janumet 50/500","56 tab","tab",204,null,null,"","sitagliptin metformin","D",[]],
["Nolvadex 10 mg","30 tab","tab",18,null,null,"","tamoxifen","X",[]],
["Norvasc 5 mg","10 tab","tab",23.5,null,null,"","amlodipine","C",[]],
["Norvasc 10 mg","10 tab","tab",25.5,null,null,"","amlodipine","C",[]],
["NovoMix 30 FlexPen","pen","pen",null,60,20,"","insulin aspart biphasic","D",["flexpen"]],
["NovoMix 50 FlexPen","pen","pen",null,60,20,"","insulin aspart biphasic","D",["flexpen"]],
["NovoRapid","cartridge","cart",null,39.5,20,"","insulin aspart","D",[]],
["Plendil 5 mg","30 tab","tab",33,null,null,"","felodipine","C",[]],
["Pletal 50 mg","20 tab","tab",44.5,null,null,"","cilostazol","AC",[]],
["Pletal 100 mg","20 tab","tab",64,null,null,"","cilostazol","AC",[]],
["Procoralan 5","28 tab","tab",50,null,null,"","ivabradine","C",["procorlan"]],
["Procoralan 7.5","28 tab","tab",50,null,null,"","ivabradine","C",["procorlan"]],
["Singulair 5 mg","14 tab","tab",77.75,null,null,"","montelukast","R",[]],
["Singulair 10 mg","14 tab","tab",84.5,null,null,"","montelukast","R",[]],
["Soliqua 100/50 SoloStar","pen","pen",287,null,null,"","insulin glargine lixisenatide","D",["solostar"]],
["Soliqua 100/33 SoloStar","pen","pen",162,null,null,"","insulin glargine lixisenatide","D",["solostar"]],
["Tritace 2.5 mg","14 tab","tab",14.5,null,null,"","ramipril","C",[]],
["Tritace Protect 10","20 tab","tab",29,null,null,"","ramipril","C",[]],
["Trivastal Retard","30 tab","tab",27.25,null,null,"","piribedil","AP",["trivestal"]],
["Vastarel MR","30 tab","tab",48.5,null,null,"","trimetazidine","C",[]],
["Zocor 10","7 tab","tab",22.75,null,null,"","simvastatin","C",[]],
["Zocor 20","14 tab","tab",60.5,null,null,"","simvastatin","C",[]],
["Zocor 40","14 tab","tab",57,null,null,"","simvastatin","C",[]],
["Xigduo 5/1000","56 tab","tab",98.5,null,null,"","dapagliflozin metformin","D",["xigidu"]],
["Atozet 10/10","10 tab","tab",96,null,null,"","ezetimibe atorvastatin","C",[]],
["Tritace Comp 5/25 mg","14 tab","tab",27,null,null,"","ramipril hydrochlorothiazide","C",["hct"]],
["Eliquis 2.5 mg","20 tab","tab",50,null,null,"","apixaban","AC",[]],
["Eliquis 5 mg","20 tab","tab",50,null,null,"","apixaban","AC",[]],
["Tegretol CR 200","20 tab","tab",7.5,null,null,"","carbamazepine controlled release","E",[]],
["Tegretol CR 400","20 tab","tab",9,null,null,"","carbamazepine controlled release","E",[]],
["Tritace Comp LS 2.5/12.5","14 tab","tab",18,null,null,"","ramipril hydrochlorothiazide","C",["hct"]],
["Concor 5 Plus","30 tab","tab",22.5,null,null,"","bisoprolol hydrochlorothiazide","C",["hct"]],
["Co-Aprovel 150/12.5 mg","14 tab","tab",47.5,null,null,"","irbesartan hydrochlorothiazide","C",["co approval","coaprovel","hct"]],
["Cozaar 50 mg","7 tab","tab",22.25,null,null,"","losartan","C",[]],
["Crestor 20 mg","7 tab","tab",48,null,null,"","rosuvastatin","C",[]],
["Crestor 10 mg","7 tab","tab",29.5,null,null,"","rosuvastatin","C",[]],
["Daflon 500 mg","30 tab","tab",30,null,null,"","diosmin hesperidin","C",[]],
["Daivobet Ointment","tube","oint",20,null,null,"","calcipotriol betamethasone","DM",[]],
["Depakine Chrono 500 mg","30 tab","tab",45,null,null,"","sodium valproate valproic acid","E",[]],
["Dostinex","2 tab","tab",54.25,null,null,"","cabergoline","H",[]],
["Depakine Syrup","bottle","syrup",16,null,null,"","sodium valproate","E",[]],
["Diamicron 60 MR","30 tab","tab",20,null,null,"","gliclazide modified release","D",["scored"]],
["Dorofen","30 tab","tab",10,null,null,"","","P",[]],
["Eloxatin 50 mg","vial","vial",500,null,null,"","oxaliplatin","X",[]],
["Eloxatin 100 mg","vial","vial",800,null,null,"","oxaliplatin","X",["eloxation"]],
["Etodolac 600 mg","10 tab","tab",15.5,null,null,"","etodolac","P",[]],
["Exforge HCT 5/160/12.5","14 tab","tab",73.5,null,null,"","amlodipine valsartan hydrochlorothiazide","C",[]],
["Exforge HCT 10/160/25","14 tab","tab",70.5,null,null,"","amlodipine valsartan hydrochlorothiazide","C",[]],
["Femara","30 tab","tab",52.59,null,null,"","letrozole","X",[]],
["Flagyl 250","20 tab","tab",5.5,null,null,"","metronidazole","AM",[]],
["Foradil Inhaler","30 tab","inh",75,null,null,"","formoterol","R",[]],
["Forxiga 5","28 tab","tab",234,null,null,"","dapagliflozin","D",[]],
["Forxiga 10","28 tab","tab",222,null,null,"","dapagliflozin","D",["forxiga10"]],
["Genuphil","50 tab","tab",20,null,null,"","glucosamine chondroitin","P",[]],
["Glucophage 1000 mg","30 tab","tab",12.5,null,null,"","metformin","D",[]],
["Januvia 50 mg","28 tab","tab",165,null,null,"","sitagliptin","D",[]],
["Januvia 100 mg","28 tab","tab",193,null,null,"","sitagliptin","D",[]],
["Lasilactone 50/20 mg","30 tab","tab",8,null,null,"","spironolactone furosemide","DI",[]],
["Lasix 40 mg","24 tab","tab",9,null,null,"","furosemide","DI",[]],
["Lipanthyl 300 mg","30 tab","tab",26,null,null,"","fenofibrate","C",[]],
["Lipitor 10 mg","7 tab","tab",28.5,null,null,"","atorvastatin","C",[]],
["Lipitor 20 mg","7 tab","tab",32,null,null,"","atorvastatin","C",[]],
["Lipitor 40 mg","7 tab","tab",46.5,null,null,"","atorvastatin","C",[]],
["Lipitor 80 mg","7 tab","tab",51,null,null,"","atorvastatin","C",[]],
["Lustral 50","7 tab","tab",26.5,null,null,"","sertraline","AD",[]],
["Mena Q","20 tab","tab",37,null,null,"","vitamin k2 menaquinone","V",["menaq"]],
["Methyltechno","30 film","film",12,null,null,"","","V",[]],
["Natrilix SR","30 tab","tab",16,null,null,"","indapamide","C",[]],
["Natrixam 1.5/5","28 tab","tab",43,null,null,"","indapamide amlodipine","C",[]],
["Natrixam 1.5/10","28 tab","tab",43,null,null,"","indapamide amlodipine","C",[]],
["Nebicard 5 mg","14 tab","tab",13,null,null,"","nebivolol","C",[]],
["Tareg 40","15 tab","tab",49,null,null,"","valsartan","C",[]],
["Tarolimus Cream","tube","cream",15,null,null,"","tacrolimus","DM",[]],
["Zestril 20","10 tab","tab",8.5,null,null,"","lisinopril","C",[]],
["Tenormin 50","14 tab","tab",7.25,null,null,"","atenolol","C",[]],
["Tenormin 100","14 tab","tab",9.5,null,null,"","atenolol","C",[]],
["Tentavair Inhaler 160 mcg","spray","inh",27,null,null,"","budesonide formoterol","R",["tentavier"]],
["Toujeo Prefilled Pen","pen","pen",null,50,15,"","insulin glargine","D",[]],
["Tresiba Prefilled Pen","pen","pen",null,70,25,"","insulin degludec","D",[]],
["Trileptal 300","50 tab","tab",116.25,null,null,"","oxcarbazepine","E",[]],
["Tegretol 200","30 tab","tab",13,null,null,"","carbamazepine","E",[]],
["Xarelto 10 mg","10 tab","tab",50,null,null,"","rivaroxaban","AC",[]],
["Xarelto 20 mg","28 tab","tab",140,null,null,"","rivaroxaban","AC",[]],
["Xarelto 15 mg","42 tab","tab",210,null,null,"","rivaroxaban","AC",[]],
["Tritace 5 mg","14 tab","tab",19,null,null,"","ramipril","C",[]],
["Nexium 20 mg","7 tab","tab",35,null,null,"","esomeprazole","G",[]],
["Zestril 5 mg","10 tab","tab",6.25,null,null,"","lisinopril","C",[]],
["Zestril 10 mg","10 tab","tab",7.5,null,null,"","lisinopril","C",[]],
["Crestor 5 mg","7 tab","tab",18,null,null,"","rosuvastatin","C",[]],
["Diamicron 80","20 tab","tab",9,null,null,"","gliclazide","D",[]],
["Diamicron 30 MR","30 tab","tab",16,null,null,"","gliclazide modified release","D",[]],
["Atozet 10/20","10 tab","tab",110,null,null,"","ezetimibe atorvastatin","C",[]],
["Orthoglobe","30 tab","tab",10,null,null,"","","P",[]],
["Brilique 60 mg","56 tab","tab",100,null,null,"","ticagrelor","C",["brilinta"]],
["Brilique 90 mg","56 tab","tab",100,null,null,"","ticagrelor","C",["brilinta"]],
["Plavix","28 tab","tab",40,null,null,"","clopidogrel","C",[]],
["Entresto 50","28 tab","tab",50,null,null,"","sacubitril valsartan","C",[]],
["Entresto 100","28 tab","tab",50,null,null,"","sacubitril valsartan","C",[]],
["Entresto 200","28 tab","tab",50,null,null,"","sacubitril valsartan","C",[]],
["Ryzodeg","pen","pen",100,null,null,"","insulin degludec aspart","D",["eyzodeg"]],
["Aprovel 150","14 tab","tab",47.5,null,null,"","irbesartan","C",["approval"]],
["Aprovel 300","14 tab","tab",42,null,null,"","irbesartan","C",["approval"]],
["Enerzair Breezhaler","30 cap","inh",null,null,null,"50% من سعر التوريد","indacaterol glycopyrronium mometasone","R",["enerzair"]],
["Spiriva","inhaler","inh",null,null,null,"50% من سعر التوريد","tiotropium","R",[]],
["Anoro Ellipta","inhaler","inh",null,null,null,"50% من سعر التوريد","umeclidinium vilanterol","R",[]],
["Co-Aprovel 300/12.5 mg","14 tab","tab",45,null,null,"","irbesartan hydrochlorothiazide","C",["co approval","coaprovel","hct"]],
["Breztri","inhaler","inh",null,null,null,"50% من سعر التوريد","budesonide glycopyrronium formoterol","R",["brezetri"]],
["Tresiba Cartridge","pen","cart",null,70,25,"","insulin degludec","D",[]]
];
